### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by msche** [reportmill/SnapTea#2]
I'm trying to set up a simple helloworld example to see how snapkit works using teavm to show the UI in the browser. This is the class I created as example:

```
public class App extends ViewOwner {

    static {
        System.setProperty("os.name", "TeaVM");
        snaptea.TV.set();
    }

    public View createUI()  { return new Label("Hello World"); }

    public static void main(String[] args) {
        //System.setProperty("os.name", "TeaVM");
        //TV.set();
        new App().setWindowVisible(true);
    }

}
```

And within gradle I have included the following dependcies for TeaVM:

```
    implementation group: 'org.teavm', name: 'teavm-cli', version: "$teavmVersion"
    implementation "org.teavm:teavm-classlib:$teavmVersion"
    implementation group: 'org.teavm', name: 'teavm-jso', version: "$teavmVersion"
    implementation group: 'org.teavm', name: 'teavm-jso-apis', version: "$teavmVersion"
```

When I start the main method I get the following exception:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'org.teavm.jso.browser.Window org.teavm.jso.browser.Window.current()'
	at org.teavm.jso.browser.Window.current(Native Method)
	at org.teavm.jso.dom.html.HTMLDocument.current(HTMLDocument.java:55)
	at snaptea.TVViewEnv.getScriptRoots(TVViewEnv.java:125)
	at snaptea.TVViewEnv.getScriptRoot(TVViewEnv.java:149)
	at snaptea.TVViewEnv.set(TVViewEnv.java:180)
	at snaptea.TV.set(TV.java:223)
```

I'm running the application on a MAC1.

Any clue what could be wrong?

**Comment by reportmill** [comment]
I’m on the road today, but here is a build.grade that I usually use:

https://github.com/reportmill/TVMApps/blob/master/build.gradle

Jeff

**Comment by msche** [comment]
Thanks for your quick reply. I will have a look at it and see whether it fixes my issue

**Comment by msche** [comment]
It is now working. Thanks

**Comment by reportmill** [comment]
Thanks for giving SnapKit/TeaVM a try (I haven’t had much of that :-)). Feel free to reach out any time and let me know if you have any feedback.

My current project is to make SnapKit/SnapCharts codeable in the browser as kind of a “Java Notebook” (like Jupyter or Matlab, but with Java). I have the fundamentals working, but it still needs a couple months to be useful. :-)

	https://reportmill.com/SnapCharts/#Notebook <https://reportmill.com/SnapCharts/#Notebook>

jeff


Jeff Martin ***@***.*** ***@***.***>>
